In [2]:
import numpy as np

## np.zero by default it fills zero 


In [5]:
t1 = np.zeros((3),dtype=np.int32) 
print("1D array")
print(t1)

t2 = np.zeros((3,2),dtype = np.int32) 
print("2D array") 
print(t2) 

t3 = np.zeros((3,3,3),dtype = np.int32) 
print("3D array") 
print(t3)

1D array
[0 0 0]
2D array
[[0 0]
 [0 0]
 [0 0]]
3D array
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


## np.ones() by default it fills one :

In [9]:
t1 = np.ones((3),dtype=np.int32) 
print("1D array")
print(t1)

t2 = np.ones((3,2),dtype = np.int32) 
print("2D array") 
print(t2) 

t3 = np.ones((3,2,3),dtype = np.int32) 
print("3D array") 
print(t3)

1D array
[1 1 1]
2D array
[[1 1]
 [1 1]
 [1 1]]
3D array
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


## np.eye() identity matrix , one on digonal

In [16]:
t = np.eye((3),dtype = np.int32) 
print(t)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [17]:
t = np.eye(2,3)
print(t)

[[1. 0. 0.]
 [0. 1. 0.]]


## np.empty () random value generate: 

In [24]:
t = np.empty(7) 
print(t)

[9.34577196e-307 9.34598246e-307 1.60218491e-306 1.69119873e-306
 1.24611673e-306 1.05699581e-307 7.29839350e-312]


## np.arange() ,(start , end-1 , step) : 

In [3]:
ar = np.arange(1,10) 
print(ar) 
ar = np.arange(1,10,2) 
print(ar)  
ar = np.arange(10,1,-1)  
print(ar)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2]


## np.linspace() , internally divide  in equal parts 

In [4]:
d = np.linspace(1,10,5) 
print(d)

[ 1.    3.25  5.5   7.75 10.  ]


In [5]:
v, d = np.linspace(1,10,3,retstep= True)  
print("difference", v)  
print(d)

difference [ 1.   5.5 10. ]
4.5


## np.random.rand() , generate some random values between 0 to 1: 

In [8]:
rand = np.random.rand(5)  # value between 0 to 1 
print(rand)  


[0.88113801 0.53554157 0.27867955 0.8787037  0.59044039]


In [26]:
## for integer 
rand = np.random.randint(10,20)  
print(rand) 


19
