In [1]:
import numpy as np

## np.zero by default it fills zero 


In [5]:
t1 = np.zeros((3),dtype=np.int32) 
print("1D array")
print(t1)

t2 = np.zeros((3,2),dtype = np.int32) 
print("2D array") 
print(t2) 

t3 = np.zeros((3,3,3),dtype = np.int32) 
print("3D array") 
print(t3)

1D array
[0 0 0]
2D array
[[0 0]
 [0 0]
 [0 0]]
3D array
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
