In [1]:
import numpy as np 

In [5]:
a = np.array([1,2,3,4,5]) 
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [6]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [4]:
ab = np.array((1,2,3,4,5,6))

In [5]:
ab

array([1, 2, 3, 4, 5, 6])

In [6]:
dic = np.array({"a":1, "b":2,"c":3}) 
dic

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [8]:
s = np.array({"a":4,"b":5,"c":4}) 
s

array({'a': 4, 'b': 5, 'c': 4}, dtype=object)

In [2]:
sh = np.ones((2,3)) 

In [3]:
sh

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
sh2 = np.zeros((4,3)) 

In [5]:
sh2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
sh3 = np.eye(3) 

In [9]:
sh3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
sh4 = np.arange(2,10,2) 

In [5]:
sh4

array([2, 4, 6, 8])