In [5]:
import numpy as np 

In [6]:
a = np.array([1,2,3,4,5]) 
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [7]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [8]:
ab = np.array((1,2,3,4,5,6))

In [9]:
ab

array([1, 2, 3, 4, 5, 6])

In [10]:
dic = np.array({"a":1, "b":2,"c":3}) 
dic

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [11]:
s = np.array({"a":4,"b":5,"c":4}) 
s

array({'a': 4, 'b': 5, 'c': 4}, dtype=object)

In [12]:
sh = np.ones((2,3)) 

In [13]:
sh

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
sh2 = np.zeros((4,3)) 

In [15]:
sh2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
sh3 = np.eye(3) 

In [17]:
sh3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
sh4 = np.arange(2,10,2) 

In [19]:
sh4

array([2, 4, 6, 8])

In [25]:
sh5 = np.linspace(1,10,5)

In [26]:
sh5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
ac = np.array([1,2,3,4,5,6]) 
ac

array([1, 2, 3, 4, 5, 6])

TypeError: reshape() missing 1 required positional argument: 'shape'