In [1]:
import numpy as np 

In [5]:
a = np.array([1,2,3,4,5]) 
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [6]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [4]:
ab = np.array((1,2,3,4,5,6))

In [5]:
ab

array([1, 2, 3, 4, 5, 6])

In [6]:
dic = np.array({"a":1, "b":2,"c":3}) 
dic

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)